version: '3'


volumes:
  eventrack_app_data: {}
  eventrack_postgres_data: {}


networks:
  backend: {}


services:
  # Eventrack application
  eventrack_app:
    build: .
    restart: always
    networks:
      - backend
    env_file:
      # You need to have this file to be able to work with docker
      - ~/.docker/secrets/eventrack.prod.env
    environment:
      - CFG_STATIC_ROOT=/app/static
      - CFG_MEDIA_ROOT=/var/eventrack/media
    volumes:
      - "eventrack_app_data:/var/eventrack"
    links:
      - eventrack_redis:redis
      - eventrack_postgres:postgres
    depends_on:
      - eventrack_redis
      - eventrack_postgres


  # DB container
  eventrack_postgres:
    image: postgres:9.6
    restart: always
    networks:
      - backend
    volumes:
      - "eventrack_postgres_data:/var/lib/postgresql/data"


  # Redis container
  eventrack_redis:
    image: redis:4.0.11
    networks:
      - backend


  # Daphne service
  eventrack_daphne:
    build: .
    command: bash -c "daphne -b 0.0.0.0 -p 8000 eventrack.asgi:application"
    ports:
      - "8000"
    env_file:
      # You need to have this file to be able to work with docker
      - ~/.docker/secrets/eventrack.prod.env
    networks:
      - backend
    links:
      - eventrack_redis:redis
    depends_on:
      - eventrack_redis


  # Worker service
  eventrack_worker:
    build: .
    command: bash -c "python manage.py runworker channels"
    env_file:
      # You need to have this file to be able to work with docker
      - ~/.docker/secrets/eventrack.prod.env
    networks:
      - backend
    links:
      - eventrack_redis:redis
      - eventrack_postgres:postgres
    depends_on:
      - eventrack_redis
      - eventrack_postgres
